version: '3.8'
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=redmine
    ports:
      - '5432:5432'
    volumes: 
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local